backend:
  name: github
  repo: clblamires/ninesjournal
  branch: master
  site_domain: ninesjournal.com
media_folder: "images"
collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Episodes" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Recorded Date", name: "recorded", widget: "string", default: "Month 01, 2019"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Episode", name: "episode", widget: "string"}
      - {label: "Adventure", name: "adventure", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  # - label: "Pages"
  #   name: "pages"
  #   files:
  #     - label: "Bag of Holding"
  #       name: "bagofholding"
  #       file: "bagofholding.html"
  #       fields:
  #         - {label: Title, name: title, widget: string}
  #         - {label: "Body", name: "body", widget: "markdown"}
  - label: "Party"
    name: "party"
    files:
      - label: "Number Nine"
        name: "numbernine"
        file: "party/numbernine.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Hebo"
        name: "hebo"
        file: "party/hebo.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Eclipse"
        name: "eclipse"
        file: "party/eclipse.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Petra"
        name: "petra"
        file: "party/petra.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Ezio"
        name: "ezio"
        file: "party/ezio.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Luna"
        name: "luna"
        file: "party/luna.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Oromis"
        name: "oromis"
        file: "party/oromis.html"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      # - label: "Locations Page"
      #   name: "locations"
      #   file: "site/content/locations.yml"
      #   fields:
      #     - {label: Title, name: title, widget: string}
      #     - {label: Intro, name: intro, widget: markdown}
      #     - label: Locations
      #       name: locations
      #       widget: list
      #       fields:
      #         - {label: Name, name: name, widget: string}
      #         - {label: Address, name: address, widget: string}
